### ISSUE TITLE
Address ability to view inventories

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate#121]
## Acceptance Criteria

1. View inventories in table format.
2. Selecting one row should open up details on the left side of the screen.
3. Should only be viewable.
4. Click on pencil icon on the side to open up the modal or something of this nature.
5. Support bulk delete as well.
6. Support adding a single inventory item and bulk upload as well.

## Technical Information

- have a side panel to display more information about the selected inventory.

**Comment by mohit2530** [comment]
I think we should make editing the existing inventory a separate page. that would give us more control over view Vs edit mode as well. since we are dealing with tables here, we would want to build it accordingly. but at the same time we also do want the drawer component to display items anchored on the left side of the screen if there are any inventories to display.

**Comment by earmuff-jam** [comment]
Splitting editing an inventory on another ticket - https://github.com/earmuff-jam/climate/issues/124 .

**Comment by earmuff-jam** [comment]
Redesigning bookmarks inventories features to support categories. We want to support `categories` and display categories on top. Then we would want to display list of inventories with okaish details. when the user clicks on the inventory, they see more details. Something like this - 
![image](https://github.com/earmuff-jam/climate/assets/114630634/593c01fa-cdf0-443f-a024-c17933c45397)
